apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- networkpolicy.yaml
- pvc.yaml
- serviceaccount.yaml
- scc-binding.yaml
- service.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/managed-by: llama-stack-operator
    app.kubernetes.io/part-of: llama-stack
